### ISSUE TITLE
Compatibility issues with Java 1.9 JDK

### ISSUE THREAD

**Issue by ajoz** [karczews/UtilsVerifier#10]
I have JDK 1.9 installed on my machine. Currently, I'm getting exceptions when building the project from the command line:

```sh
Compiling with JDK Java compiler API.
error: Source option 1.5 is no longer supported. Use 1.6 or later.
error: Target option 1.5 is no longer supported. Use 1.6 or later.
```

This is described in the migration document: https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-77874D97-46F3-4DB5-85E4-2ACB5F8D760B

The most important thing from that document is:

> The supported -source/-target values are 9 (the default), 8, 7, and 6 (6 is deprecated, and a warning is displayed when this value is used).
>
> In JDK 8, -source and -target values of 1.5/5 and earlier were deprecated and caused a warning to be generated. In JDK 9, those values cause an error.

For the time being, I'm just switching to 1.6 in the `build.gradle`. I'm just wondering if we should take this into consideration?

**Comment by karczews** [comment]
1.6 sounds reasonable. Lets switch.

**Comment by ajoz** [comment]
Integrated to master in PR #11
