### ISSUE TITLE
Declared compatibility with Java 1.5 but used API from Java 1.7

### ISSUE THREAD

**Issue by ajoz** [karczews/UtilsVerifier#7]
Minor thing, but it makes the IDE unhappy. 

In the `build.gradle` it is defined:

```gradle
sourceCompatibility = JavaVersion.VERSION_1_5
targetCompatibility = JavaVersion.VERSION_1_5
```

But some Java 1.7 API is used in `verifyPrivateConstructor` method.
- `AssertionError(String message, Throwable cause)`
- `ReflectiveOperationException`

Either we bump the API to `VERSION_1_7` or we drop the usage of said constructor and class.

What do you think?

**Comment by karczews** [comment]
I wanted to keep compatibility as low as possible. 
If its not a big hassle maybe lets try dumping usage of this constructor and class.
Maybe `AssertionError(Object detailMessage)` will do just fine to provide meaningful message ?

**Comment by ajoz** [comment]
I agree that `AssertionError(Object detailMessage)` will be enough because a simple Java `interface` is a class without a constructor. This way we can force the code:

```java
try {
            constructor = classUnderTest.getDeclaredConstructor();
            if (!suppressPrivateConstructorCheck && !Modifier.isPrivate(constructor.getModifiers())) {
                throw new AssertionError("Constructor should be private");
            }
        } catch (final NoSuchMethodException noSuchMethod) {
            throw new AssertionError(classUnderTest.getSimpleName() + " has no constructor", noSuchMethod);
        }
```
To get straight to `NoSuchMethodException` handling. Example stacktrace from the `AssertionError`:

```java
java.lang.AssertionError: NoConstructor has no constructor
	at com.github.karczews.utilsverifier.UtilsVerifier.verifyPrivateConstructor(UtilsVerifier.java:202)
	at com.github.karczews.utilsverifier.UtilsVerifier.verify(UtilsVerifier.java:92)
	at ...
Caused by: java.lang.NoSuchMethodException: com.github.karczews.utilsverifier.subjects.NoConstructor.<init>()
	at ...
	... 26 more
```
As you see, this `AssertionError(String message, Throwable cause)` doesn't bring much value.

**Comment by ajoz** [comment]
Pull Request: https://github.com/karczews/UtilsVerifier/pull/9

**Comment by ajoz** [comment]
Fixed
